
database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  password: ${PGPASSWORD}
  user_database: 'hello'
  connectionTimeoutMillis: 3000
  user_dbclient: 'knex'
runtimeConfig:
  entrypoint: dist/entrypoint.js
