# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension 
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/operon/main/operon-config.schema.json

database:
  hostname: 'localhost'
  port: 5432
  username: 'postgres'
  password: ${PGPASSWORD}
  user_database: 'hello'
  system_database: 'hello_systemdb'
  connectionTimeoutMillis: 3000
  user_dbclient: 'knex'
