# To enable auto-completion and validation for this file in VSCode, install the RedHat YAML extension
# https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

# yaml-language-server: $schema=https://raw.githubusercontent.com/dbos-inc/dbos-transact/main/dbos-config.schema.json

language: node
database_url: ${DBOS_DATABASE_URL}
database:
  app_db_client: drizzle
  migrate:
    - npx drizzle-kit migrate
runtimeConfig:
  entrypoints:
    - dist/operations.js
